#!/usr/bin/env bash

echo "INFO: Installing Homebrew to your system... this may take some time"

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "INFO: Installing Ansible, if you haven't gotten some coffee now, it's time to."
brew install ansible

echo "INFO: This will take some time depending on the amount of programs you are going to install."
echo "INFO: I'd suggest you, to go to lunch now"

ansible-galaxy install -r requirements.yml
ansible-playbook ${1}.yml


echo "INFO: Your mac is ready now. Have Fun!"